[package]
name = "allinone"
version = "0.1.0"
authors = ["r0x <r00txxyyzz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
consul-rs = {git = "https://github.com/liyiheng/consul-rs", branch = "master"}
#local-ip = "0.1"
local_ipaddress = "0.1.3"
serde = "1.0.117"
lazy_static = "1.4.0"

#[dependencies.pnet]
#version = "0.26.0"